[config]
enable_custom_labels = true

[custom_labels."bug ğŸ›"]
description = """Fixes a bug in the code"""
[custom_labels."build ğŸ› ï¸"]
description = """Items related to continuous integration or continuous deployment"""
[custom_labels."dependencies â¬†ï¸"]
description = """Modifications of the project dependencies"""
[custom_labels."docker ğŸ‹"]
description = """Updates to docker configuration"""
[custom_labels."documentation ğŸ“—"]
description = """Updates to documentation"""
[custom_labels."enhancement âœ¨"]
description = """Adds new features or modifies existing ones"""
[custom_labels."github actions ğŸ› ï¸"]
description = """Adds or modifies GitHub Actions"""
[custom_labels."python ğŸ"]
description = """Updates that modify python code"""
[custom_labels."tests ğŸ§ª"]
description = """Updates to tests"""
